
import TilesPage from "@/components/shared/TilesPage";
import Link from "next/link";
import React from "react";
import { FaArrowLeft } from "react-icons/fa";

export const metadata = {
  title: "DBL | Tiles",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Link
        href="/"
        className="inline-flex mt-6 items-center gap-2 text-sm font-semibold text-gray-700 hover:text-gray-900 hover:shadow-sm ml-6 md:ml-10 lg:ml-60"
      >
        <FaArrowLeft />
        Back to Home Page
      </Link>
      <TilesPage />
    </div>
  );
};

export default page;
